language:
    csharp
sudo: required
mono: none 
dotnet: 3.0

os:
  - linux

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=true

before_script:
    - dotnet restore ".\ConsoleCalculator\ConsoleCalculator.sln"
    
script:
    - dotnet build ".\ConsoleCalculator\ConsoleCalculator.sln" -c Release
    - dotnet test ".\ConsoleCalculator\ConsoleCalculator.sln" -c Release -v n